# Site settings
title: Rinkesh Purohit
email: rinkeshpurohit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi I'm Rinkesh Purohit from Bangalore.<br>B.Tech. (C.S.E.) 2015 passout.<br>
  My skills are HTML, CSS, Sass, JavaScript, JQuery, Bootstrap.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  rinkeshpurohit

# Build settings
markdown: kramdown
